import {
    // create naive ui
    create,
    NA,
    NAvatar,
    NBadge,
    NModal,
    NButton,
    NCard,
    NConfigProvider,
    NDialogProvider,
    NDropdown,
    NForm,
    NFormItem,
    NGlobalStyle,
    // component
    NH1,
    NH2,
    NIcon,
    NImage,
    NInput,
    NLayout,
    NLayoutContent,
    NLayoutFooter,
    NLayoutHeader,
    NLayoutSider,
    NLoadingBarProvider,
    NMenu,
    NMessageProvider,
    NP,
    NPopover,
    NResult,
    NSpace,
    NTabPane,
    NTabs,
    NText,
    NTooltip, NSelect, NNotificationProvider, NDataTable, NDivider, NGrid, NFormItemGi, NScrollbar
} from 'naive-ui'

export default create({
    components: [
        NH1,
        NH2,
        NP,
        NText,
        NA,
        NIcon,
        NImage,
        NAvatar,
        NButton,
        NBadge,
        NTabs,
        NTabPane,
        NDropdown,
        NMenu,
        NResult,
        NCard,
        NForm,
        NFormItem,
        NInput,
        NTooltip,
        NPopover,
        NSpace,
        NLayout,
        NLayoutSider,
        NLayoutHeader,
        NLayoutContent,
        NLayoutFooter,
        NGlobalStyle,
        NConfigProvider,
        NDialogProvider,
        NMessageProvider,
        NLoadingBarProvider, NSelect, NDivider,
        NNotificationProvider, NDataTable, NModal,NGrid,NFormItemGi,NScrollbar
    ]
})