spring:
  application:
    name: meta-sphere
  data:
    redis:
      host: 172.16.2.10
      port: 6379
      password: c1$4T&9pW#z2Q@7vL
      database: 5
  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 300000
      auto-commit: true
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  messages:
    basename: i18n/commons,i18n/api,i18n/bug,i18n/case,i18n/plan,i18n/project,i18n/system
    default-locale: zh_CN
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: test-hub-quartz
            instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
          jobStore:
            #            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore #持久化配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis-flex:
  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3306/meta-sphere?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
jwt:
  secret: K4lgrcqOP576NhrtYJhuQD8DdMYfZtb58hWdJaTjPbk=
  access-token-validity: 7200000 #2h
  refresh-token-validity: 604800000 # 7d

logging:
  level:
    web: info # Web 模块日志级别
    org.springframework.web: info  # Spring Web 框架日志
    org.springframework.boot.web.servlet: info  # Servlet 容器日志
    org.springframework.security: info